name = "MaassTheorem"
uuid = "a1b2c3d4-e5f6-7890-abcd-ef1234567890"

[deps]
AppleAccelerate = "13e28ba4-7ad8-5781-acae-3021b1ed3924"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
AppleAccelerate = "0.4, 0.5"
CairoMakie = "0.11, 0.12, 0.13"
DifferentialEquations = "7"
DrWatson = "2"
Flux = "0.14, 0.15, 0.16"
JSON3 = "1"
StableRNGs = "1"
julia = "1.10, 1.11, 1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
